"""Verilator runner — the primary simulator path."""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from .base import RunResult


class VerilatorFailed(Exception):
    """Verilator build/run failed; caller should fall back to Icarus."""


class VerilatorRunner:
    """Drives a cocotb test via Verilator (with `--coverage --build`).

    Relies on the Makefile generated by tb_gen.render.render() inside tb_dir.
    The Makefile drives `make` which calls cocotb + verilator internally.
    """

    def run(self, tb_dir, seed: int, num_seq: int, timeout_sec: int = 600) -> RunResult:
        tb_dir = Path(tb_dir)
        if not (tb_dir / "Makefile").exists():
            raise VerilatorFailed(f"No Makefile in {tb_dir}")

        if shutil.which("verilator") is None:
            raise VerilatorFailed("verilator not installed")

        stdout_path = tb_dir / "verilator_run.stdout"
        stderr_path = tb_dir / "verilator_run.stderr"

        env_overlay = {
            "SIM": "verilator",
        }
        cmd = [
            "make",
            "-C", str(tb_dir),
            f"SEED={seed}",
            f"NUM_SEQ={num_seq}",
        ]

        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout_sec,
                env={**__import__("os").environ, **env_overlay},
            )
        except subprocess.TimeoutExpired as exc:
            raise VerilatorFailed(f"verilator timed out after {timeout_sec}s") from exc

        stdout_path.write_text(proc.stdout or "", encoding="utf-8", errors="ignore")
        stderr_path.write_text(proc.stderr or "", encoding="utf-8", errors="ignore")

        coverage_dat = tb_dir / "coverage.dat"
        coverage_xml = tb_dir / "coverage.xml"
        functional_cov = tb_dir / "functional_cov.json"

        if proc.returncode != 0:
            raise VerilatorFailed(
                f"verilator make exited {proc.returncode}; tail stderr:\n"
                f"{(proc.stderr or '')[-1000:]}"
            )

        return RunResult(
            exit_code=proc.returncode,
            stdout_path=stdout_path,
            stderr_path=stderr_path,
            coverage_dat=coverage_dat if coverage_dat.exists() else None,
            coverage_xml=coverage_xml if coverage_xml.exists() else None,
            functional_cov=functional_cov if functional_cov.exists() else None,
            log_tail=(proc.stdout or "")[-1500:],
        )
